### ISSUE TITLE
Compiling RuleSet failed: Unexpected property test

### ISSUE THREAD

**Issue by Miselrkba** [abea/demo-apos-snipcart#1]
Hello.

I followed the steps mentioned in https://apostrophecms.com/blog/using-snipcart-and-apostrophe-for-simple-e-commerce 
and upon running ```npm run dev`` I was left with this error:

``` 
(node:2756) UnhandledPromiseRejectionWarning: Error: Compiling RuleSet failed: Unexpected property test in condition (at ruleSet[1].rules[1].resource.test: resource => {
        currentResource = resource
        return true
      })
```

I googled a bit and found that the issue was a missing vue loader package. 
The issue was fixed by running npm ``` install vue-loader@next ```

**Comment by abea** [comment]
Thanks, @Miselrkba. That older demo uses the alpha version of Apostrophe 3, so I'll update that as well. If you are looking for a production starter for A3 projects, please see https://github.com/apostrophecms/a3-boilerplate/ or use the `@apostrophecms/cli` tool.
